### ISSUE TITLE
MainActivity doesn't load upcoming events on the first run after installation or clearing app's storage.

### ISSUE THREAD

**Issue by ixrk** [partymakers/partymaker#46]
## Problem

When a user runs the app for a first time, the login activity is launched, but it doesn't have enough time to sign in before the app tries to load upcoming events, therefore PERMISSION_DENIED exception is thrown. 

```
com.google.firebase.firestore.FirebaseFirestoreException: PERMISSION_DENIED: Missing or insufficient permissions.
```

## Possible solutions

* Only load the UI after user is logged in and display loading symbol in the meantime.
* Divide MainActivity into two activities. The first one is visible on the application launcher. It will only handle login and starting the dashboard. The second handles that dashboard.

**Comment by ixrk** [comment]
#47 is similar in nature. We should apply a generalized solution.

**Comment by bkaryna** [comment]
You've solved it by moving Firestore access to repository classes 🥳
